server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }

    location /api/users {
        proxy_pass http://10.0.138.103:8081/api/users;
    }

    location /api/products {
        proxy_pass http://10.0.138.103:8082/api/products;
    }
}